language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools 28.0.3
    - android-29
    - platform-tools
    - tools
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
    - ./gradlew test
